name: Dotnet build and test workflow

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Run tests
        run: cd backend && dotnet restore && dotnet test --configuration Release
      - name: "Build backend Docker container"
        run: |
          cp .env.example .env
          docker-compose build backend
