name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: deployment_environment
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Deployment"
        run: |
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${{secrets.USER}}@${{secrets.HOST_NAME}} \
          "cd ~/code/kats-games && \
          git checkout master && \
          git pull origin master && \
          docker-compose up --build -d && \
          exit"
