name: Deploy to working server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH access
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval `ssh-agent -s`
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - name: "Build backend Docker container"
        run: |
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $USER@$HOST_NAME
          "cd $TARGET_DIR &&
          git checkout master &&
          git pull origin master &&
          docker-compose up --build -d &&
          exit"
