name: Dotnet build and test workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      
      - name: Install dependencies
        run: cd backend && dotnet restore

      - name: Build solution
        run: cd backend && dotnet build --configuration Release
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Install dependencies
        run: cd backend && dotnet restore

      - name: Run tests
        run: cd backend && dotnet test --configuration Release
