name: Frontend build workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build frontend Docker container"
      run: |
        cp .env.example .env
        docker-compose build frontend
